 services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017 
    volumes:
      - mongo:/data 
    environment:
      - MONGO_INITDB_ROOT_USERNAME:satan
      - MONGO_INITDB_ROOT_PASSWORD:satanas   
  mongo-express:
     image: mongo-express
     container_name: mongo_express
     depends_on:
       - mongodb
     ports:
       - 8081:8081
     environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME:satan
       - ME_CONFIG_MONGODB_ADMINPASSWORD:satanas
       - ME_CONFIG_MONGODB_SERVER=mongodb
 volumes:
   mongo: {}
           
 